directory: https://acme-staging-v02.api.letsencrypt.org/directory
# directory: https://acme-v02.api.letsencrypt.org/directory

storage:
  type: s3
  region: 'ap-northeast-1'
  bucket: '...'
  # prefix: '...'
  # kms_key_id: 'arn:aws:kms:...'

# storage:
#   type: filesystem
#   path: ./storage

challenge_responders:
  - route53: {}

      master_domain: example.jp
      challenge_domain: challenge.example.jp

account_key_passphrase: password
certificate_key_passphrase: secret
